const properties = [

  {
    id: 2,
    title: "HOUSE in Bangalore",
    location: "45 Indiranagar, Bangalore, KA",
    property_type: "House",
    images: ["/images/prop3.png", "/images/prop4.png"],
    latitude: 12.9716,
    longitude: 77.5946,
    price: 5500000,
    bhk: 1,
    status: "Sold",
    amenities: ["Hospital", "Park", "School"],
    owner: {
      username: "Riya",
      email: "riya@example.com",
      contact_no: "+919874563210",
    },
  },
  {
    id: 3,
    title: "HOUSE in Coimbatore",
    location: "202 Avinashi Rd, Coimbatore, TN",
    property_type: "House",
    images: ["/images/prop5.png", "/images/prop6.png"],
    latitude: 11.0168,
    longitude: 76.9558,
    price: 5000000,
    bhk: 3,
    status: "Under Construction",
    amenities: ["Hospital", "Gym", "Mall"],
    owner: {
      username: "Mohan",
      email: "mohan@example.com",
      contact_no: "+919812345678",
    },
  },
  {
    id: 4,
    title: "HOUSE in Madurai",
    location: "22 Alagar Kovil Rd, Madurai, TN",
    property_type: "House",
    images: ["/images/prop7.png", "/images/prop8.png"],
    latitude: 9.9252,
    longitude: 78.1198,
    price: 7000000,
    bhk: 4,
    status: "Available",
    amenities: ["School", "Supermarket", "Park"],
    owner: {
      username: "Priya",
      email: "priya@example.com",
      contact_no: "+919823456789",
    },
  },
  {
    id: 5,
    title: "APARTMENT in Chennai",
    location: "OMR, Sholinganallur, Chennai, TN",
    property_type: "Apartment",
    images: ["/images/prop9.png", "/images/prop10.png"],
    latitude: 12.9081,
    longitude: 80.2271,
    price: 4000000,
    bhk: 3,
    status: "Available",
    amenities: ["Hospital", "Park"],
    owner: {
      username: "Arjun",
      email: "arjun@example.com",
      contact_no: "+919900112233",
    },
  },
  {
    id: 6,
    title: "CONDO in Coimbatore",
    location: "Peelamedu, Coimbatore, TN",
    property_type: "Condo",
    images: ["/images/imagecopy.png", "/images/imagecopy8.png"],
    latitude: 11.03,
    longitude: 77.03,
    price: 5000000,
    bhk: 3,
    status: "Sold",
    amenities: ["Gym", "School", "Mall"],
    owner: {
      username: "Ananya",
      email: "ananya@example.com",
      contact_no: "+919800223344",
    },
  },
  {
    id: 7,
    title: "APARTMENT in Bangalore",
    location: "Whitefield, Bangalore, KA",
    property_type: "Apartment",
    images: ["/images/imagecopy2.png", "/images/imagecopy9.png"],
    latitude: 12.97,
    longitude: 77.75,
    price: 4000000,
    bhk: 2,
    status: "Available",
    amenities: ["Hospital", "Park", "Supermarket"],
    owner: {
      username: "Vikram",
      email: "vikram@example.com",
      contact_no: "+919811223344",
    },
  },
  {
    id: 8,
    title: "APARTMENT in Tiruchirappalli",
    location: "Thillai Nagar, Trichy, TN",
    property_type: "Apartment",
    images: ["/images/imagecopy3.png", "/images/imagecopy10.png"],
    latitude: 10.7905,
    longitude: 78.7047,
    price: 3000000,
    bhk: 1,
    status: "Under Construction",
    amenities: ["Park", "Gym"],
    owner: {
      username: "Divya",
      email: "divya@example.com",
      contact_no: "+919877665544",
    },
  },
  {
    id: 9,
    title: "CONDO in Chennai",
    location: "Nungambakkam, Chennai, TN",
    property_type: "Condo",
    images: ["/images/imagecopy4.png", "/images/imagecopy11.png"],
    latitude: 13.063,
    longitude: 80.242,
    price: 6000000,
    bhk: 3,
    status: "Available",
    amenities: ["School", "Mall", "Supermarket"],
    owner: {
      username: "Sanjay",
      email: "sanjay@example.com",
      contact_no: "+919899887766",
    },
  },
  {
    id: 10,
    title: "CONDO in Bangalore",
    location: "Koramangala, Bangalore, KA",
    property_type: "Condo",
    images: ["/images/imagecopy5.png", "/images/imagecopy12.png"],
    latitude: 12.934,
    longitude: 77.61,
    price: 7000000,
    bhk: 2,
    status: "Sold",
    amenities: ["Hospital", "Gym", "Park"],
    owner: {
      username: "Lakshmi",
      email: "lakshmi@example.com",
      contact_no: "+919812343210",
    },
  },
  {
    id: 11,
    title: "APARTMENT in Salem",
    location: "Fairlands, Salem, TN",
    property_type: "Apartment",
    images: ["/images/imagecopy6.png", "/images/imagecopy13.png"],
    latitude: 11.6643,
    longitude: 78.146,
    price: 5000000,
    bhk: 4,
    status: "Available",
    amenities: ["School", "Mall", "Gym"],
    owner: {
      username: "Harish",
      email: "harish@example.com",
      contact_no: "+919755443322",
    },
  },
  {
    id: 12,
    title: "CONDO in Madurai",
    location: "KK Nagar, Madurai, TN",
    property_type: "Condo",
    images: ["/images/imagecopy7.png", "/images/imagecopy14.png"],
    latitude: 9.93,
    longitude: 78.13,
    price: 4000000,
    bhk: 2,
    status: "Under Construction",
    amenities: ["Hospital", "School", "Park"],
    owner: {
      username: "Meena",
      email: "meena@example.com",
      contact_no: "+919700112255",
    },
  },
  {
    id: 13,
    title: "HOUSE in Coimbatore",
    location: "Saibaba Colony, Coimbatore, TN",
    property_type: "House",
    images: ["/images/imagecopy.png", "/images/imagecopy15.png"],
    latitude: 11.03,
    longitude: 76.94,
    price: 3000000,
    bhk: 3,
    status: "Available",
    amenities: ["Mall", "Park"],
    owner: {
      username: "Ramesh",
      email: "ramesh@example.com",
      contact_no: "+919744556677",
    },
  },
];

export default properties;